### ISSUE TITLE
minplayers map vote Bug change map random when the vote start

### ISSUE THREAD

**Issue by mouadhbr** [evandrocoan/MultiModServer#25]
minplayers map vote change map random when the vote start /run off vote start

**Comment by evandrocoan** [comment]
Hi,

May you tell me the steps to reprocuce this issue on defaut amxx server
install?

Example:
1. Install the plugin:
2. Set the cvar gal_min_map to abc.txt
3. ...

See the support section for help:
1. https://forums.alliedmods.net/showthread.php?t=273019#Support

**Comment by evandrocoan** [comment]
Non response from the author, closing it.
