### ISSUE TITLE
Make runoff voting more customizable

### ISSUE THREAD

**Issue by mo0nsniper** [evandrocoan/MultiModServer#33]
Hi,

I would like to suggest to make runoff voting more configurable.
For example I would like to have runoff voting take into account all the map options that had the maximum amount of votes so an option doesn't have to get more than 50% of the votes, just choose between the options with the most amount of votes. This is because when there are many players on the server it's hard for more than half of them to agree on one or two maps.

My suggestion would be to make a CVAR for the percentage of players that need to vote for an option. So if the percentage is set very low the options with the most votes would be choose for runoff.
And make another CVAR for the number of maps to be included in runoff voting. So someone could choose to have two, three or maybe all maps with the highest number of votes in runoff voting.

So having the first CVAR set to 0.5 and the second CVAR set to 2 will preserve the actual behavior but will also allow someone to modify it. 

Thank you

**Comment by evandrocoan** [comment]
There are 4 cases to be treated to choose which maps are part in the run off, on the lines [5735-5750](https://github.com/evandrocoan/Galileo/blob/8ee45bb4f1772997b55f36f3480f19485e7e5cef/scripting/galileo.sma#L5735-L5750):

1. numberOfMapsAtFirstPosition > 2 
1. numberOfMapsAtFirstPosition == 2
1. numberOfMapsAtSecondPosition == 1
1. numberOfMapsAtFirstPosition == 1 && numberOfMapsAtSecondPosition > 1

For now I can think of only to add more maps to the run off for the first case scenario. 
What do you think of?

**Comment by mo0nsniper** [comment]
Yes, the first option sounds the best.

**Comment by mo0nsniper** [comment]
Thanks :)
