### ISSUE TITLE
FEATURE REQUEST

### ISSUE THREAD

**Issue by ish12321** [evandrocoan/MultiModServer#35]
Hello,
is it possible that if I use mp_maxrounds then timeleft shows "Xx Rounds Left"

**Comment by evandrocoan** [comment]
Yes, but you need to install another plugin to do it. Currently the plugin doing it is the default `timeleft.amxx`.

1. https://www.google.com/search?q=timeleft.amxx
1. [Timeleft as Roundtime (AcidoX)](https://forums.alliedmods.net/showthread.php?p=879073)
