### ISSUE TITLE
Map Change on Rounds

### ISSUE THREAD

**Issue by ish12321** [evandrocoan/MultiModServer#36]
When we have map change vote [on last round ofcourse] if the round ends before the vote is complete the map changes to anything but not as per votes :( 

Please fix it :|

**Comment by evandrocoan** [comment]
1. status
1. version
1. meta list
1. amxx list
1. amxx cvars

* Paste here everything from the **status** command *except* the player list.
* Paste here the entire result from the **version**, **meta list** and **amxx list** commands.
* Paste here ***only*** the CVARs that contain **galileo.amxx** in the last column
  from the **amxx cvars** command. They will be grouped together.

https://forums.alliedmods.net/showthread.php?t=273019#Support

**Comment by ish12321** [comment]
Can't provide console stuff like status version
as I don't have access to console 
Still I'm using latest rehlds with latest regamedll_cs with reunion 
Amxmodx 1.8.2

The galileo config file is below 
I use mp_maxrounds 30
[galileo.zip](https://github.com/evandrocoan/Galileo/files/624084/galileo.zip)

**Comment by ish12321** [comment]
Why not someone else try this plugin with 3 players
Not 1 
use mp_maxrounds instead of timelimit with the same cvars as mine 
When map change menu occurs simply kill complete team before vote overs 
And check

**Comment by evandrocoan** [comment]
If you don't have access the your game server's console, join your server and type the following
commands in your game's console:
status
rcon_password "YOUR_RCON_PASSWORD"
rcon version
rcon meta list
rcon amxx list
rcon amxx cvars

**Comment by ish12321** [comment]
Please can anyone test on his server
We have set no rcon pass
Sorry for that
But providing those informations is not possible for now 

Please check this please
It's troubling our players a lot

**Comment by evandrocoan** [comment]
I already fixed this issue: https://github.com/evandrocoan/Galileo/issues/3 on the latest version. What is your version?

If you cannot get the server info does it mean you cannot update the plugin. And if you cannot update the plugin, there is no use to you fix it.

But if you can update the plugin, it mean you can create a RCON password as you have access to the server files. So I do not see why you cannot provide the information.

When I to start the development again, I will occasionally reproduce it, if it is bugged like this. Do you use `mp_timelimit` or `mp_roundlimit`?

**Comment by ish12321** [comment]
i use mp_maxrounds 30

**Comment by ish12321** [comment]
and soon we will change our gamepanel and will give you the results you need too :)

**Comment by ish12321** [comment]
Checked ?

**Comment by evandrocoan** [comment]
Checked what?

**Comment by evandrocoan** [comment]
Closing it due not provided the requested information.

**Comment by evandrocoan** [comment]
Reopening in case it is not fixed yet, but still waiting the author response, requested by https://github.com/evandrocoan/Galileo/issues/46#issuecomment-269420752

**Comment by ish12321** [comment]
Is the plugin working or it needs test?

**Comment by evandrocoan** [comment]
If you do not test, you will not know.
If it is not working, then send the `_galileo.log` file.

**Comment by ish12321** [comment]
Fixed

**Comment by evandrocoan** [comment]
Nice, but I have no idea how it got fixed. 
What I did was rewrote several things because the new features required a better algorithm, as the last one was not clear how to be extended.
