### ISSUE TITLE
New end on round voting algorithm

### ISSUE THREAD

**Issue by evandrocoan** [evandrocoan/MultiModServer#38]
### New end on round voting algorithm

The current algorithm uses a fixed value as 400 seconds before the last 2:30 minutes.

Now implement a heuristic which counts every end round, how much time the round took and how much time remains to the end of map. In base with it, calculate the correct round to start the voting. Also add a fail safe to block map change until the voting is completed, whether it is by round, frags or time.

Also, to perform the voting exactly when the map is about the end considering the shifts by the voting maps times related on:

1. https://github.com/evandrocoan/Galileo/issues/20 Vote starting at 7 minutes before map end
1. https://github.com/evandrocoan/Galileo/issues/8 _ Limit the maximum voting time start

1. [x] Implement the cvar `gal_endofmapvote_start`'s feature heuristics for mp_fraglimit and mp_maxrounds/wins.
1. [ ] ~**May be also to detect map time anomalies as the time limit being set to and the time left changes from 10 to 1 minute. This is due the new fail safe implemented on:**~
 * 55a675018dfecb7398b0e6773759b96a9a7a1f69 Improved the voting end fail safe code structure.

Now if the time limit is abnormally set, the map will never change because the voting will never start and its state set to over. Then we need to implement a clever end voting fail safe:

1. [ ] ~To auto set the voting as over when there is not enough time to perform a full voting, or just to start the voting right away.~
1. [ ] ~To start the voting anyways when there is not enough time for a full voting, but just to perform the first voting part not allowing the runoff.~

**Comment by ish12321** [comment]
Is it done ? ., 
What about in end by rounds make the round doesn't end before the voting has completely not ended ? 
If that's possible it would make it very better

**Comment by evandrocoan** [comment]
When you are using rounds, the voting should start some rounds before the map change, so there should be enough time to the voting to finish. But I will consider adding a fail safe to block map change until the voting is completed.

It is a open issue, then I is not implemented yet. See:

1. Mastering Issues _ https://guides.github.com/features/issues/

**Comment by ish12321** [comment]
Please finish it asap as it will solve my issue #36

**Comment by ish12321** [comment]
Can you atleast do this and release a working small release
Too important
Please
