### ISSUE TITLE
Rtv or map change

### ISSUE THREAD

**Issue by ish12321** [evandrocoan/MultiModServer#54]
People on my server complain me that in rtv after its finished the map change countdown sounds is incorrect....

It's not 8 76 5 4 3 2 1 ... But something like 5 8 4 2 1 or something other incorrect

**Comment by evandrocoan** [comment]
I entered on my server, did the rtv, and the sounds are correct. 
Everytime you do rtv on your server that happens?

**Comment by evandrocoan** [comment]
I think is happened on when the rtv was finished near the round end.
On the next version I am blocking the count down from being started twice.
