### ISSUE TITLE
gal_startvote changing the map immediately after the vote

### ISSUE THREAD

**Issue by spark512** [evandrocoan/MultiModServer#65]
Hey, i'm not sure why but rtv is not following the proper configurations, it's changing the map immediately.

Here's my config:
https://gist.github.com/spark512/6805c9dc09bdd34b0e0105f53f14ae9f

**Comment by spark512** [comment]
Why does gal_startvote immediately change the map?

https://github.com/evandrocoan/MultiModServer/blob/master/plugins/addons/amxmodx/scripting/galileo.sma#L12036

https://github.com/evandrocoan/MultiModServer/blob/master/plugins/addons/amxmodx/scripting/galileo.sma#L9402

In brad's plugin, gal_startvote followed the configurations for normal end map vote. Can you make it follow the configurations here?

**Comment by spark512** [comment]
Sorry, after checking the code i see that rtv follows the `gal_endonround_rtv` cvar properly. RTV works fine.

https://github.com/evandrocoan/MultiModServer/blob/master/plugins/addons/amxmodx/scripting/galileo.sma#L10137-L10147

The `gal_startvote` command however changes the map immediately. Can you make the gal_startvote command follow the `gal_endonround_rtv` cvar as well? That's how gal_startvote worked in brad's plugin...

https://github.com/evandrocoan/MultiModServer/blob/master/plugins/addons/amxmodx/scripting/galileo.sma#L12036

**Comment by evandrocoan** [comment]
If you want to `gal_startvote` not change the map immediately you need to pass the argument `-nochange`:

> ![image](https://cloud.githubusercontent.com/assets/5332158/26323335/d59b2c54-3f04-11e7-9c66-6325ac9dd390.png)

> https://forums.alliedmods.net/showthread.php?t=273019#Brief

If you want to the map to change after the round end, I can add a new argument as `-roundend`. So you would call it as `gal_startvote -roundend`.

**Comment by spark512** [comment]
The default `gal_startvote` command, entered with no extra parameters should follow galileo's configurations, not change the map immediately. It's better to add a paramenter `-changenow` to make the it change immediately instead of having the default like that. That's different from brad's version.

 The `-nochange` command only sets the nextmap value and lets the server(or other mapchanges) change the map after time runs out.

You should keep the same default behavior as brad did.

Either that, or implement a cvar that allows changing how the `gal_startvote` command works by default..

**Comment by evandrocoan** [comment]
It is written on the Brad documentation:
> Forces a map vote to begin and the map will be changed once 
the next map has been determined.  If the "-nochange" argument
is supplied, the map will not be changed by Galileo, which is useful 
when you have a different plugin handling the actual changing 
of the map.
https://forums.alliedmods.net/showthread.php?t=77391#commands

The default call to `gal_startvote` must change the map as soon as the voting ends. Rephrasing:
>the map will be changed once the next map has been determined

This is what a default call to `gal_startvote` does on Brads plugin. Its also what it does on mine too.
I did not change anything.

___

> The default `gal_startvote` command, entered with no extra parameters should follow galileo's configurations

There is no configuration for the `gal_startvote` command. The only configuration there is, is for the `say rtv` command:
```pawn
// Indicates when a map should end after the RTV voting is finished.
// If selected a value higher than 0, this cvar indicates also the players
// minimum number necessary to allow the last round to be finished when
// the time runs out.
// For example, if this cvar value is set to 2, and there are only 1 player
// on the server, the round will end immediately.
//
// 0               - end immediately after the voting finished.
//
// player's number - end after the current round, only when there are at
//                   least the `player's number` quantity on the server.
//
// Default: 0
gal_endonround_rtv 2
```

**Comment by spark512** [comment]
> the map will be changed once the next map has been determined
Will be changed by galileo, and this depends on the configurations. I have brad's old plugin and our old configurations, i can show you if you want.

Calling gal_startvote (no parameters) makes the vote and then changes the map after the round ends, it changes the map on new round beginning.  That's how i have it configured and that's how it's been running for years..
