### ISSUE TITLE
Remove the bug fix for the AMXX 182 menu filling on AMXX 183

### ISSUE THREAD

**Issue by evandrocoan** [evandrocoan/MultiModServer#72]
> ![image](https://user-images.githubusercontent.com/5332158/28130160-6762c244-670c-11e7-91b7-e1dd039947d0.png)

> It is a bug fix for the AMXX 182 menu filling:
[QUOTE='https://www.amxmodx.org/api/newmenus/menu_addblank']
When using slot=1 this might break your menu.
[/QUOTE]
So I added the `OFF` text as filler and be able to put the `back` and `next` buttons at the bottom of the page.

https://forums.alliedmods.net/showthread.php?p=2534749#post2534749

[QUOTE=BeNq!;2534826]I have AMXX 1.8.3-re.[/QUOTE]

I only implemented it for AMXX 182, so if you use AMXX 183, it will also be like that. 
So, I can look into adding better support for AMXX 183, removing this workaround/kludge.

**Comment by fred0r** [comment]
Are you planning a fix ?

**Comment by evandrocoan** [comment]
I am not sure anymore, I am not playing for now or a long time. But how much urgent is this?

**Comment by fred0r** [comment]
Thx
