### ISSUE TITLE
Galileo / emptymapcycle / hltv

### ISSUE THREAD

**Issue by fred0r** [evandrocoan/MultiModServer#80]
---
### Summary
HLTV Proxy is counted as regular player and so the emptymapcycle never starts

### Expected behavior
Server should switch to the emptymapcycle if there are no real players connected

### Actual behavior
Server doesnt start the emptymapcycle when HLTV is connected

### Environment

* Operating system and version:
  * [x ] Linux - Debian 9

* AMX Mod X version:
  * v1.8.3-5147

* Galileo Version:
  *  v5.8.1-918

**Comment by fred0r** [comment]
Why 'Severity: minor' ?
There are a lot of Servers which have a HLTV-Proxy recording all played Maps.
This unfortunately breaks the whole 'emptymapcycle'-Feature :(

**Comment by evandrocoan** [comment]
Minor because should not be much hard to fix. I am not sure why it is counting the `HLTV` as a server player.

I think you can fix this just by setting the cvar `gal_server_players_count` from 0 to 1:
```c++
// If enabled, it will ignore players on the spectator team. This will
// have effect when the plugin need counting the server players. Only
// works for Counter-Strike/CZ mod.
//
// If you also enabled the cvar `gal_emptyserver_change`, it will cause
// the empty-cycle feature to work when there are spectators on server.
//
// 0 - disabled this feature.
// 1 - enable this feature.
//
// Default: 0
gal_server_players_count 0
```

Can you try this setting?

**Comment by evandrocoan** [comment]
This seems to be a bug on the `AMXX 5147`, because when I am counting players, I am using:
```pawn
        get_players( players, playersCount, "ch" );
```
Where the `ch` flags mean:
1. "c" - do not include bots
1. "h" - do not include HLTV proxies

https://www.amxmodx.org/api/amxmodx/get_players

**Comment by fred0r** [comment]
i've `gal_server_players_count 0` set.
Well - at least i think the hltv is counted as a regular player, because i've never seen any of the 'emptymapcycle-maps' when the server is 'empty'.
i'll ask the amxmodx guys.

**Comment by evandrocoan** [comment]
It could be that the empty cycle feature is just not working. Can you [record a log](https://forums.alliedmods.net/showthread.php?t=273019#Support) while letting the server running some time when it is empty and then post here the `_galileo_log.txt` file?

The server should be able to enter on the empty cycle feature. If it does not enter, the log should help know why it is not entering.

**Comment by fred0r** [comment]
ok - i'll report back.

**Comment by regener** [comment]
I have tried it with 1.8.3 build 5177 wth latest Galileo and it does not change to emptycycle if there is a HLTV online (alone).
~~So I guess it is fixed already.~~

**Comment by evandrocoan** [comment]
> regener: I have tried it with 1.8.3 build 5177 wth latest Galileo and it does **not** change to emptycycle if there is a HLTV online (alone).

Perhaps you meant is does change instead of does not.
Because it is a bug if it does not change the map when the HLTV is online.

**Comment by regener** [comment]
Aww yes, I meant that sorry for confusing.

**Comment by evandrocoan** [comment]
No problem. Thanks for testing it out!
