### ISSUE TITLE
[galileo] - 'Cannot start the voting. The cvar gal_server_players_count is not supported on this Game Mod.'

### ISSUE THREAD

**Issue by fred0r** [evandrocoan/MultiModServer#91]
---
### Summary
after a new map starts on cstrike theres:
`Cannot start the voting. The cvar gal_server_players_count is not supported on this Game Mod.` 
beside that message everything seem to work as expected.

coherent set cvars seem to be:
```
gal_server_players_count "1"
gal_emptyserver_wait "10"
gal_emptyserver_mapfile "addons/amxmodx/configs/galileo/emptycycle_maplist.txt"
gal_srv_start "0"
gal_game_crash_recreation "0"
gal_endofmapvote "1"
```
### Expected behavior

No Error.
### Actual behavior
i get `Cannot start the voting. The cvar gal_server_players_count is not supported on this Game Mod.` after a new map starts - 
 seen on a hltv-demo recorded from that server running galileo.
### Environment
* Operating system and version:
  * Linux - Debian 10 + curernt updates
* AMX Mod X version:
  * v1.10-latest
* Game Mod:
  * latest rehls/regamedll_cs on cstrike
* Galileo Version:
  * v5.9.1-931 (latest)

**Comment by evandrocoan** [comment]
https://github.com/evandrocoan/MultiModServer/blob/bcb9e037c7accd1d4bb7e95623357b7787fadf2f/plugins/addons/amxmodx/scripting/galileo.sma#L1967

I did not tested galieo with rehlds, but if you know this will work, you can change that line to this and recompile galileo:
```
    g_isColorChatSupported = true;
```

**Comment by fred0r** [comment]
thanks - i recompiled and will check.

**Comment by fred0r** [comment]
it doesnt appear anymore ingame, but i still see that message when watching a hltv-demo - its printed in the console.

**Comment by fred0r** [comment]
using https://github.com/Mistrick/MapManagerModular now
